"""initial tables

Revision ID: 5f8408ca4bfd
Revises:
Create Date: 2025-06-19 09:04:04.410309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f8408ca4bfd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "followers",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("follower_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "follower_id"),
    )
    op.create_index(
        "idx_followers_follower_id", "followers", ["follower_id"], unique=False
    )
    op.create_table(
        "tweets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tweets_author_id", "tweets", ["author_id"], unique=False
    )
    op.create_table(
        "attachments",
        sa.Column("tweet_id", sa.BigInteger(), nullable=False),
        sa.Column("link", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["tweets.id"],
        ),
        sa.PrimaryKeyConstraint("tweet_id", "link"),
    )
    op.create_table(
        "likes",
        sa.Column("tweet_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["tweets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("tweet_id", "user_id"),
    )
    op.create_index("idx_likes_user_id", "likes", ["user_id"], unique=False)
    op.create_table(
        "medias",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tweet_id", sa.BigInteger(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["tweets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("medias")
    op.drop_index("idx_likes_user_id", table_name="likes")
    op.drop_table("likes")
    op.drop_table("attachments")
    op.drop_index("idx_tweets_author_id", table_name="tweets")
    op.drop_table("tweets")
    op.drop_index("idx_followers_follower_id", table_name="followers")
    op.drop_table("followers")
    op.drop_table("users")
    # ### end Alembic commands ###
